<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'App\\App' => $baseDir . '/App/App.php',
    'App\\Models\\Delivery' => $baseDir . '/App/Models/Delivery.php',
    'App\\Models\\Inventory' => $baseDir . '/App/Models/Inventory.php',
    'App\\Models\\Product' => $baseDir . '/App/Models/Product.php',
    'App\\Models\\Theme' => $baseDir . '/App/Models/Theme.php',
    'App\\Models\\User' => $baseDir . '/App/Models/User.php',
    'App\\core\\Auth' => $baseDir . '/App/core/Auth.php',
    'App\\core\\Database' => $baseDir . '/App/core/Database.php',
    'App\\core\\Request' => $baseDir . '/App/core/Request.php',
    'App\\core\\Router' => $baseDir . '/App/core/Router.php',
    'ComposerAutoloaderInitfe1cd51c7e9b8a48512ad590d96a26b3' => $vendorDir . '/composer/autoload_real.php',
    'Composer\\Autoload\\ClassLoader' => $vendorDir . '/composer/ClassLoader.php',
    'Composer\\Autoload\\ComposerStaticInitfe1cd51c7e9b8a48512ad590d96a26b3' => $vendorDir . '/composer/autoload_static.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
