<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfe1cd51c7e9b8a48512ad590d96a26b3
{
    public static $classMap = array (
        'App\\App' => __DIR__ . '/../..' . '/App/App.php',
        'App\\Models\\Delivery' => __DIR__ . '/../..' . '/App/Models/Delivery.php',
        'App\\Models\\Inventory' => __DIR__ . '/../..' . '/App/Models/Inventory.php',
        'App\\Models\\Product' => __DIR__ . '/../..' . '/App/Models/Product.php',
        'App\\Models\\Theme' => __DIR__ . '/../..' . '/App/Models/Theme.php',
        'App\\Models\\User' => __DIR__ . '/../..' . '/App/Models/User.php',
        'App\\core\\Auth' => __DIR__ . '/../..' . '/App/core/Auth.php',
        'App\\core\\Database' => __DIR__ . '/../..' . '/App/core/Database.php',
        'App\\core\\Request' => __DIR__ . '/../..' . '/App/core/Request.php',
        'App\\core\\Router' => __DIR__ . '/../..' . '/App/core/Router.php',
        'ComposerAutoloaderInitfe1cd51c7e9b8a48512ad590d96a26b3' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'Composer\\Autoload\\ComposerStaticInitfe1cd51c7e9b8a48512ad590d96a26b3' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitfe1cd51c7e9b8a48512ad590d96a26b3::$classMap;

        }, null, ClassLoader::class);
    }
}
